version: '3'

services:

  rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    container_name: microservices-rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - './rabbitmq_data:/var/lib/rabbitmq/mnesia'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - microservices-sync

networks:
  microservices-sync:
     driver: bridge